// ── ÜLKE TANIMLARI ──────────────────────────────────────────────────────────
// Bu dosya tüm ülkelerin çıktı sütunlarını tanımlar.
// Yeni ülke eklemek için sadece bu dosyayı düzenlemen yeterli.

const COUNTRIES = {
  kz: { label: 'Kazakistan', suffix: '_kazakistan' },
  rs: { label: 'Sırbistan',  suffix: '_sirbistan'  },
  iq: { label: 'Irak',       suffix: '_irak'        },
  ge: { label: 'Gürcistan',  suffix: '_gurcistan'   },
  cy: { label: 'KKTC',       suffix: '_kktc'        },
  ru: { label: 'Rusya',      suffix: '_rusya'        },
  ba: { label: 'Bosna',      suffix: '_bosna'        },
  be: { label: 'Belçika',    suffix: '_belcika'      },
  de: { label: 'Almanya',  suffix: '_almanya'  },
  nl: { label: 'Hollanda', suffix: '_hollanda' },
  xk: { label: 'Kosova',     suffix: '_kosova'       },
  mk: { label: 'Makedonya',  suffix: '_makedonya'    },
  ru: { label: 'Rusya',      suffix: '_rusya'      },
  uz: { label: 'Özbekistan', suffix: '_ozbekistan' },
};

const KZ_COLS = [
  'E-Fatura Seri Numarası',
  'Madde Kodu',
  'MENŞEİ -EN',
  'MENŞEİ -RU',
  'Asorti Barkodu',
  'SKU',
  'Renk Açıkmalası EN',
  'GTİP',
  'ALT GRUBU -EN',
  'Ürün Açıklaması EN',
  'Ürün Açıklaması RU',
  'Miktar',
  'Fiyat',
  'MATERYAL -EN',
  'MATERYAL -RU',
  'ALT GRUBU Açıklama',
  'EBAT Açıklama',
  'BRÜT',
  'NET',
];

const RS_INV = [
  { out: 'COUNTRY OF ORIGIN', src: 'MENŞEİ -EN'         },
  { out: 'MASTER ITEM CODE',  src: 'Asorti Barkodu'      },
  { out: 'ITEM CODE',         src: 'SKU'                 },
  { out: 'ITEM DESCRIPTION',  src: 'ALT GRUBU -EN'       },
  { out: 'ITEM NAME',         src: 'Ürün Açıklaması EN'  },
  { out: 'UNIT',              src: 'Birim Cinsi (1)'     },
  { out: 'QTY',               src: 'Miktar'              },
  { out: 'UNIT PRICE',        src: 'Fiyat'               },
  { out: 'TOTAL AMOUNT TRY',  src: '__CALC__'            },
  { out: 'HS CODE',           src: 'GTİP'                },
  { out: 'MATERIAL',          src: 'MATERYAL -EN'        },
  { out: 'ITEM NAME-Serb',    src: 'Ürün Açıklaması XS'  },
  { out: 'COLOR SERB',        src: 'Renk Açıkmalası XS'  },
  { out: 'MATERIAL SERB',     src: 'MATERYAL -XS'        },
  { out: 'DIMENSION',         src: 'EBAT Açıklama'       },
  { out: 'BRÜT',              src: 'BRÜT'                },
  { out: 'NET',               src: 'NET'                 },
];

const SIMPLE_MAPS = {

  iq: [
    { out: 'MENŞEİ -EN',         src: 'MENŞEİ -EN'         },
    { out: 'SKU',                src: 'SKU'                 },
    { out: 'ALT GRUBU -EN',      src: 'ALT GRUBU -EN'       },
    { out: 'Ürün Açıklaması EN', src: 'Ürün Açıklaması EN'  },
    { out: 'Madde Açıklaması',   src: 'Madde Açıklaması'    },
    { out: 'Miktar',             src: 'Miktar'              },
    { out: 'Fiyat',              src: 'Fiyat'               },
    { out: 'Miktar X Fiyat',     src: '__CALC__'            },
    { out: 'GTİP',               src: 'GTİP'                },
    { out: 'BRÜT',               src: 'BRÜT'                },
    { out: 'NET',                src: 'NET'                 },
  ],

  cy: [
    { out: 'MENŞEİ Açıklama',        src: 'MENŞEİ Açıklama'       },
    { out: 'Asorti Barkodu',         src: 'Asorti Barkodu'         },
    { out: 'SKU',                    src: 'SKU'                    },
    { out: 'ALT GRUBU Açıklama',     src: 'ALT GRUBU Açıklama'     },
    { out: 'Madde Açıklaması',       src: 'Madde Açıklaması'       },
    { out: 'Miktar',                 src: 'Miktar'                 },
    { out: 'ÜRÜN ANA GRUBU',         src: 'ÜRÜN ANA GRUBU'         },
    { out: 'E-Fatura Seri Numarası', src: 'E-Fatura Seri Numarası' },
    { out: 'BRÜT',                   src: 'BRÜT'                   },
    { out: 'NET',                    src: 'NET'                    },
  ],

  ru: [
    { out: 'E-Fatura Seri Numarası', src: 'E-Fatura Seri Numarası' },
    { out: 'Madde Kodu',             src: 'Madde Kodu'             },
    { out: 'MENŞEİ -EN',             src: 'MENŞEİ -EN'             },
    { out: 'MENŞEİ -RU',             src: 'MENŞEİ -RU'             },
    { out: 'Asorti Barkodu',         src: 'Asorti Barkodu'         },
    { out: 'SKU',                    src: 'SKU'                    },
    { out: 'Barkod',                 src: 'Barkod'                 },
    { out: 'Renk Açıkmalası EN',     src: 'Renk Açıkmalası EN'     },
    { out: 'GTİP',                   src: 'GTİP'                   },
    { out: 'ALT GRUBU -EN',          src: 'ALT GRUBU -EN'          },
    { out: 'Ürün Açıklaması EN',     src: 'Ürün Açıklaması EN'     },
    { out: 'ALT GRUBU -RU',          src: 'ALT GRUBU -RU'          },
    { out: 'Ürün Açıklaması RU',     src: 'Ürün Açıklaması RU'     },
    { out: 'Miktar',                 src: 'Miktar'                 },
    { out: 'Fiyat',                  src: 'Fiyat'                  },
    { out: 'Net Tutar (D)',          src: 'Net Tutar (D)'          },
    { out: 'MATERYAL -EN',           src: 'MATERYAL -EN'           },
    { out: 'MATERYAL -RU',           src: 'MATERYAL -RU'           },
    { out: 'ALT GRUBU Açıklama',     src: 'ALT GRUBU Açıklama'     },
    { out: 'EBAT Açıklama',          src: 'EBAT Açıklama'          },
    { out: 'BRÜT',                   src: 'BRÜT'                   },
    { out: 'NET',                    src: 'NET'                    },
  ],

  ba: [
    { out: 'MENŞEİ -EN',         src: 'MENŞEİ -EN'        },
    { out: 'Asorti Barkodu',     src: 'Asorti Barkodu'     },
    { out: 'SKU',                src: 'SKU'                },
    { out: 'ALT GRUBU -EN',      src: 'ALT GRUBU -EN'      },
    { out: 'Ürün Açıklaması EN', src: 'Ürün Açıklaması EN' },
    { out: 'Miktar',             src: 'Miktar'             },
    { out: 'Fiyat (D)',          src: 'Fiyat (D)'          },
    { out: 'Net Tutar (D)',      src: 'Net Tutar (D)'      },
    { out: 'GTİP',               src: 'GTİP'               },
    { out: 'MATERYAL -EN',       src: 'MATERYAL -EN'       },
    { out: 'Renk Açıkmalası EN', src: 'Renk Açıkmalası EN' },
    { out: 'EBAT Açıklama',      src: 'EBAT Açıklama'      },
    { out: 'BRÜT',               src: 'BRÜT'               },
    { out: 'NET',                src: 'NET'                },
  ],

  be: [
    { out: 'MENŞEİ -EN',             src: 'MENŞEİ -EN'             },
    { out: 'E-Fatura Seri Numarası', src: 'E-Fatura Seri Numarası'  },
    { out: 'Asorti Barkodu',         src: 'Asorti Barkodu'          },
    { out: 'SKU',                    src: 'SKU'                     },
    { out: 'ALT GRUBU -EN',          src: 'ALT GRUBU -EN'           },
    { out: 'Ürün Açıklaması EN',     src: 'Ürün Açıklaması EN'      },
    { out: 'Miktar',                 src: 'Miktar'                  },
    { out: 'UNIT PRICE EUR',         src: '__EUR__'                 },
    { out: 'TOTAL AMOUNT EUR',       src: '__EUR_TOTAL__'           },
    { out: 'GTİP',                   src: 'GTİP'                    },
    { out: 'MATERYAL -EN',           src: 'MATERYAL -EN'            },
    { out: 'BRÜT',                   src: 'BRÜT'                    },
    { out: 'NET',                    src: 'NET'                     },
  ],

  de: [
    { out: 'MENŞEİ -EN',             src: 'MENŞEİ -EN'            },
    { out: 'E-Fatura Seri Numarası', src: 'E-Fatura Seri Numarası' },
    { out: 'Asorti Barkodu',         src: 'Asorti Barkodu'         },
    { out: 'SKU',                    src: 'SKU'                    },
    { out: 'ALT GRUBU -EN',          src: 'ALT GRUBU -EN'          },
    { out: 'Ürün Açıklaması EN',     src: 'Ürün Açıklaması EN'     },
    { out: 'Miktar',                 src: 'Miktar'                 },
    { out: 'UNIT PRICE EUR',         src: '__EUR__'                },
    { out: 'TOTAL AMOUNT EUR',       src: '__EUR_TOTAL__'          },
    { out: 'GTİP',                   src: 'GTİP'                   },
    { out: 'MATERYAL -EN',           src: 'MATERYAL -EN'           },
    { out: 'BRÜT',                   src: 'BRÜT'                   },
    { out: 'NET',                    src: 'NET'                    },
  ],

  nl: [
    { out: 'MENŞEİ -EN',             src: 'MENŞEİ -EN'            },
    { out: 'E-Fatura Seri Numarası', src: 'E-Fatura Seri Numarası' },
    { out: 'Asorti Barkodu',         src: 'Asorti Barkodu'         },
    { out: 'SKU',                    src: 'SKU'                    },
    { out: 'ALT GRUBU -EN',          src: 'ALT GRUBU -EN'          },
    { out: 'Ürün Açıklaması EN',     src: 'Ürün Açıklaması EN'     },
    { out: 'Miktar',                 src: 'Miktar'                 },
    { out: 'UNIT PRICE EUR',         src: '__EUR__'                },
    { out: 'TOTAL AMOUNT EUR',       src: '__EUR_TOTAL__'          },
    { out: 'GTİP',                   src: 'GTİP'                   },
    { out: 'MATERYAL -EN',           src: 'MATERYAL -EN'           },
    { out: 'BRÜT',                   src: 'BRÜT'                   },
    { out: 'NET',                    src: 'NET'                    },
  ],

};